# Spring
spring:
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.62.249:3306/management?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: manage
    password: root

  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    #清除缓存
    cache: false
    mode: LEGACYHTML5 #非严格模式
    servlet:
      content-type: text/html


mybatis:
  mapper-locations: mapper/*.xml

server:
  port: 8082